### ISSUE TITLE
FRONTEND - Adicionar e fazer funcionar as ComboBox para escolher o cargo e atividade do funcionário e categoria do produto

### ISSUE THREAD

**Issue by CassianoR** [CassianoR/OlharDeMenina_WPF#115]
Prazo: Segunda-feira (09/08/2021)

**Comment by vitorpdsg** [comment]
Amanhã vou resolver o erro do BD e ver se deu certo o que fiz hj, e tá com um problema que intuí por não ter a autosugestão do VS em alguns bindings, provavelmente algo da viewmodel sendo chamada lá em cima no XAML. Mas acredito que já tá quase pronto
